Prepare data for MLP exercise

This is a quick an dirty data prep for an in-class competition of Intro to DL within MAI. 

Original dataset: https://archive.ics.uci.edu/dataset/206/relative+location+of+ct+slices+on+axial+axis

Dropping patients for simplicity though this is a major data leakage.

In [1]:
import pandas as pd

In [2]:
# load data from csv
df = pd.read_csv('slice_localization_data.csv')
df

,patientId,value0,value1,value2,value3,value4,value5,value6,value7,value8,...,value375,value376,value377,value378,value379,value380,value381,value382,value383,reference
0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.250000,-0.250000,-0.25000,...,-0.25,0.980381,0.0,0.000000,0.000000,0.0,0.0,-0.25,-0.25,21.803851
1,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.250000,-0.250000,-0.25000,...,-0.25,0.977008,0.0,0.000000,0.000000,0.0,0.0,-0.25,-0.25,21.745726
2,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.250000,-0.250000,-0.25000,...,-0.25,0.977008,0.0,0.000000,0.000000,0.0,0.0,-0.25,-0.25,21.687600
3,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.250000,-0.250000,-0.25000,...,-0.25,0.977008,0.0,0.000000,0.000000,0.0,0.0,-0.25,-0.25,21.629474
4,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.250000,-0.250000,-0.25000,...,-0.25,0.976833,0.0,0.000000,0.000000,0.0,0.0,-0.25,-0.25,21.571348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53495,96,0.591906,0.357764,0.000000,0.000000,0.552321,0.795304,0.946697,0.952227,0.84395,...,0.00,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.00,0.00,29.290398
53496,96,0.612313,0.000000,0.000000,0.000000,0.864160,0.820531,0.000000,0.938813,0.94374,...,0.00,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.00,0.00,27.945721
53497,96,0.612313,0.000000,0.000000,0.000000,0.864160,0.820531,0.000000,0.938813,0.94374,...,0.00,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.00,0.00,27.945721
53498,96,0.634921,0.904555,0.956087,0.980208,0.157664,0.000000,-0.250000,-0.250000,-0.25000,...,-0.25,0.000000,0.0,0.994967,0.806688,0.0,0.0,-0.25,-0.25,14.582997
53499,96,0.654321,0.891021,0.882244,0.979282,0.000000,0.000000,-0.250000,-0.250000,-0.25000,...,-0.25,0.000000,0.0,0.994671,0.000000,0.0,0.0,-0.25,-0.25,14.498955

In [3]:
# drop patient id
df_nop = df.drop(columns='patientId').rename(columns={'reference': 'TARGET'})
df_nop

,value0,value1,value2,value3,value4,value5,value6,value7,value8,value9,...,value375,value376,value377,value378,value379,value380,value381,value382,value383,TARGET
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.250000,-0.250000,-0.25000,-0.250000,...,-0.25,0.980381,0.0,0.000000,0.000000,0.0,0.0,-0.25,-0.25,21.803851
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.250000,-0.250000,-0.25000,-0.250000,...,-0.25,0.977008,0.0,0.000000,0.000000,0.0,0.0,-0.25,-0.25,21.745726
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.250000,-0.250000,-0.25000,-0.250000,...,-0.25,0.977008,0.0,0.000000,0.000000,0.0,0.0,-0.25,-0.25,21.687600
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.250000,-0.250000,-0.25000,-0.250000,...,-0.25,0.977008,0.0,0.000000,0.000000,0.0,0.0,-0.25,-0.25,21.629474
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.250000,-0.250000,-0.25000,-0.250000,...,-0.25,0.976833,0.0,0.000000,0.000000,0.0,0.0,-0.25,-0.25,21.571348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53495,0.591906,0.357764,0.000000,0.000000,0.552321,0.795304,0.946697,0.952227,0.84395,0.798303,...,0.00,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.00,0.00,29.290398
53496,0.612313,0.000000,0.000000,0.000000,0.864160,0.820531,0.000000,0.938813,0.94374,0.868504,...,0.00,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.00,0.00,27.945721
53497,0.612313,0.000000,0.000000,0.000000,0.864160,0.820531,0.000000,0.938813,0.94374,0.868504,...,0.00,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.00,0.00,27.945721
53498,0.634921,0.904555,0.956087,0.980208,0.157664,0.000000,-0.250000,-0.250000,-0.25000,-0.250000,...,-0.25,0.000000,0.0,0.994967,0.806688,0.0,0.0,-0.25,-0.25,14.582997
53499,0.654321,0.891021,0.882244,0.979282,0.000000,0.000000,-0.250000,-0.250000,-0.25000,-0.250000,...,-0.25,0.000000,0.0,0.994671,0.000000,0.0,0.0,-0.25,-0.25,14.498955

In [4]:
# prepar for split 80/20
df_nop = df_nop.sample(frac=1).reset_index(drop=True)
N = len(df_nop)
0.8 * N

42800.0

In [5]:
# split to train test
train = df_nop[:42800]
train

,value0,value1,value2,value3,value4,value5,value6,value7,value8,value9,...,value375,value376,value377,value378,value379,value380,value381,value382,value383,TARGET
0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.673369,0.000000,-0.25,-0.25,...,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,-0.25,56.667181
1,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,-0.25,...,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,-0.25,62.455880
2,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.561189,0.791667,0.00,-0.25,...,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,-0.25,57.597645
3,0.0,0.000000,0.019536,0.000000,0.640917,0.875338,0.000000,0.000000,0.00,-0.25,...,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,75.635799
4,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,-0.25,...,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,-0.25,54.977994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42795,0.0,0.000000,0.160804,0.917494,0.000000,0.000000,0.000000,-0.250000,-0.25,-0.25,...,-0.25,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.25,-0.25,16.011716
42796,0.0,0.000000,0.000000,0.137531,0.807635,0.000000,0.000000,0.000000,0.00,-0.25,...,0.00,0.999478,0.999990,0.999994,0.999718,0.000000,0.000000,0.00,0.00,32.677481
42797,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.381601,0.000000,-0.25,-0.25,...,0.00,0.000000,0.997943,0.000000,0.000000,0.982282,0.996467,0.00,-0.25,50.347706
42798,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.560280,0.000000,-0.25,-0.25,...,0.00,0.000000,0.000000,0.000000,0.000000,0.762923,0.000000,0.00,-0.25,57.145727
42799,0.0,0.583667,0.963985,0.851934,0.000000,0.000000,0.000000,0.000000,0.00,-0.25,...,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,79.817306

In [6]:
test = df_nop[42800:]
test

,value0,value1,value2,value3,value4,value5,value6,value7,value8,value9,...,value375,value376,value377,value378,value379,value380,value381,value382,value383,TARGET
42800,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.909039,0.000000,-0.250000,-0.250000,...,0.00,0.000000,0.000000,0.000000,0.000000,0.865903,0.343742,0.00,-0.25,50.410640
42801,0.00000,0.0,0.000000,0.000000,0.000000,0.793039,0.000000,0.000000,0.000000,-0.250000,...,0.00,0.000000,0.996940,0.999800,0.999976,0.998890,0.000000,0.00,-0.25,39.699727
42802,0.00000,0.0,0.000000,0.000000,0.000000,0.894451,0.915720,0.000000,0.000000,-0.250000,...,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,-0.25,73.294328
42803,0.00000,0.0,0.000000,0.000000,0.000000,0.038103,0.449785,0.000000,-0.250000,-0.250000,...,0.00,0.000000,0.000000,0.000000,0.000000,0.658903,0.000000,0.00,-0.25,53.815835
42804,0.00000,0.0,0.732570,0.930533,0.926396,0.000000,0.000000,0.000000,0.000000,-0.250000,...,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,78.117139
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53495,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.250000,-0.250000,...,0.00,0.000000,0.000000,0.999776,0.999618,0.000000,0.000000,0.00,-0.25,45.283461
53496,0.14966,0.0,0.026403,0.000000,0.104651,0.000000,0.000000,0.102208,0.972981,0.977089,...,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,29.239518
53497,0.00000,0.0,0.000000,0.775681,0.757828,0.692167,0.899152,0.000000,0.000000,0.000000,...,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00,28.034335
53498,0.00000,0.0,0.866873,0.949353,0.000000,0.000000,-0.250000,-0.250000,-0.250000,-0.250000,...,-0.25,0.992647,0.000000,0.000000,0.000000,0.000000,0.000000,-0.25,-0.25,19.075165
53499,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.819987,0.000000,0.000000,-0.250000,...,0.00,0.996863,0.999997,0.999988,0.999901,0.999993,0.998827,0.00,-0.25,47.813177

In [7]:
# export to csv files
train.to_csv('ct_slice_train.csv', index_label='ID')
test.to_csv('ct_slice_test.csv', index_label='ID')
test.drop(columns='TARGET').to_csv('ct_slice_test_noLabels.csv', index_label='ID')
tg = test['TARGET']
tg_df = pd.DataFrame(tg)
tg_df['Usage'] = 'Public'
tg_df['Usage'].iloc[5350:] = 'Private'
tg_df.to_csv('ct_slice_test_Labels.csv', index_label='ID')
tg.values[:]=0
tg.to_csv('sample_submission.csv', index_label='ID')
tg_df

/tmp/ipykernel_119532/3982171821.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  tg_df['Usage'].iloc[5350:] = 'Private'
/tmp/ipykernel_119532/3982171821.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tg_df['Usage'].iloc[5350:] = 'Private'

          TARGET    Usage
42800  50.410640   Public
42801  39.699727   Public
42802  73.294328   Public
42803  53.815835   Public
42804  78.117139   Public
...          ...      ...
53495  45.283461  Private
53496  29.239518  Private
53497  28.034335  Private
53498  19.075165  Private
53499  47.813177  Private

[10700 rows x 2 columns]

In [12]:
# sandbox submission
avg = train['TARGET'].mean()
tg.values[:]=avg
tg.to_csv('sandbox.csv', index_label='ID')